version: "3.8"

services:
  mongo:
    image: mongo:7.0
    container_name: neuroguard-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: neuroguard-backend
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    depends_on:
      - mongo
    cap_add:
      - NET_RAW
      - NET_ADMIN

  frontend:
    build: ./frontend
    container_name: neuroguard-frontend
    restart: unless-stopped
    network_mode: host
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    container_name: neuroguard-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  mongo_data:
